services:
  # React frontend service
  frontend:
    image: ghcr.io/elisiariocouto/leggen:latest-frontend
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      leggen-server:
        condition: service_healthy

  # FastAPI backend service
  leggen-server:
    image: ghcr.io/elisiariocouto/leggen:latest
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - "./data:/root/.config/leggen"  # Configuration and database directory
