REQUISITION_STATUS = {
    "CR": "CREATED",
    "GC": "GIVING_CONSENT",
    "UA": "UNDERGOING_AUTHENTICATION",
    "RJ": "REJECTED",
    "SA": "SELECTING_ACCOUNTS",
    "GA": "GRANTING_ACCESS",
    "LN": "LINKED",
    "EX": "EXPIRED",
}
